/* SPDX-License-Identifier: 0BSD */

/* posish - centralized error catalog */

#ifndef POSISH_ERROR_CATALOG_H
#define POSISH_ERROR_CATALOG_H

enum posish_error_kind {
    POSISH_ERROR_KIND_SYNTAX,
    POSISH_ERROR_KIND_BUILTIN,
    POSISH_ERROR_KIND_RUNTIME,
    POSISH_ERROR_KIND_SYSTEM
};

enum posish_error_id {
    POSERR_UNTERMINATED_COMMAND_SUBSTITUTION,
    POSERR_UNTERMINATED_BACKTICK_SUBSTITUTION,
    POSERR_UNTERMINATED_DOLLAR_SINGLE_QUOTE,
    POSERR_UNTERMINATED_PARAMETER_EXPANSION,
    POSERR_TRAILING_BACKSLASH,
    POSERR_UNTERMINATED_QUOTE,
    POSERR_UNEXPECTED_EOF_MATCHING_QUOTE,
    POSERR_UNEXPECTED_TOKEN,
    POSERR_MISSING_REDIRECTION_OPERAND,
    POSERR_AMBIGUOUS_REDIRECTION,
    POSERR_INVALID_FD_REDIRECTION,
    POSERR_UNSUPPORTED_TOKENS_AFTER_GROUP,
    POSERR_COMPLEX_SYNTAX_UNIMPLEMENTED,

    POSERR_CD_INVALID_OPTION,
    POSERR_CD_TOO_MANY_ARGUMENTS,
    POSERR_CD_HOME_NOT_SET,
    POSERR_CD_OLDPWD_NOT_SET,

    POSERR_PWD_INVALID_OPTION,
    POSERR_PWD_TOO_MANY_ARGUMENTS,

    POSERR_UMASK_INVALID_OPTION,
    POSERR_UMASK_TOO_MANY_OPERANDS,
    POSERR_UMASK_INVALID_MODE,

    POSERR_PRINTF_EXPECTED_NUMERIC_VALUE,
    POSERR_PRINTF_MISSING_FORMAT_CHARACTER,
    POSERR_PRINTF_UNSUPPORTED_CONVERSION,
    POSERR_PRINTF_MISSING_FORMAT_OPERAND,

    POSERR_KILL_AMBIGUOUS_JOB,
    POSERR_KILL_INVALID_JOB_SPEC,
    POSERR_KILL_NO_SUCH_JOB,

    POSERR_ALIAS_INVALID_NAME,
    POSERR_ALIAS_NOT_FOUND,
    POSERR_UNALIAS_INVALID_OPTION,
    POSERR_UNALIAS_MISSING_OPERAND,
    POSERR_UNALIAS_INVALID_NAME,
    POSERR_UNALIAS_NOT_FOUND,
    POSERR_GETOPTS_MISSING_OPERANDS,
    POSERR_GETOPTS_INVALID_VARIABLE_NAME,
    POSERR_GETOPTS_ILLEGAL_OPTION,
    POSERR_GETOPTS_OPTION_REQUIRES_ARGUMENT,
    POSERR_HASH_INVALID_OPTION,
    POSERR_TYPE_MISSING_OPERAND,
    POSERR_JOBSPEC_AMBIGUOUS,
    POSERR_JOBSPEC_INVALID,
    POSERR_JOBSPEC_NO_SUCH,
    POSERR_WAIT_UNSUPPORTED_OPERAND,
    POSERR_FG_JOB_CONTROL_DISABLED,
    POSERR_FG_TOO_MANY_ARGUMENTS,
    POSERR_FG_NO_CURRENT_JOB,
    POSERR_BG_JOB_CONTROL_DISABLED,
    POSERR_BG_NO_CURRENT_JOB,

    POSERR_COMMAND_INVALID_OPTION,
    POSERR_SHIFT_INVALID_COUNT,
    POSERR_SHIFT_TOO_MANY_ARGUMENTS,
    POSERR_SHIFT_COUNT_OUT_OF_RANGE,
    POSERR_SET_INVALID_OPTION_NAME,
    POSERR_SET_INVALID_OPTION,
    POSERR_LOOP_INVALID_COUNT,
    POSERR_LOOP_TOO_MANY_ARGUMENTS,
    POSERR_LOOP_ONLY_IN_LOOP,
    POSERR_RETURN_NUMERIC_ARGUMENT_REQUIRED,
    POSERR_RETURN_TOO_MANY_ARGUMENTS,
    POSERR_RETURN_OUTSIDE_CONTEXT,
    POSERR_DOT_FILENAME_ARGUMENT_REQUIRED,
    POSERR_DOT_FILE_NOT_FOUND,
    POSERR_UNSET_INVALID_OPTION,
    POSERR_UNSET_INVALID_FUNCTION_NAME,
    POSERR_EXPORT_INVALID_OPTION,
    POSERR_EXPORT_INVALID_VARIABLE_NAME,
    POSERR_READ_OPTION_REQUIRES_ARGUMENT,
    POSERR_READ_INVALID_OPTION,
    POSERR_READONLY_INVALID_OPTION,
    POSERR_TRAP_INVALID_SIGNAL,
    POSERR_TRAP_MISSING_CONDITION,
    POSERR_EXIT_NUMERIC_ARGUMENT_REQUIRED,
    POSERR_EXIT_TOO_MANY_ARGUMENTS
};

struct posish_error_def {
    enum posish_error_id id;
    enum posish_error_kind kind;
    const char *fmt;
};

const struct posish_error_def *posish_error_lookup(enum posish_error_id id);
const char *posish_error_kind_name(enum posish_error_kind kind);

#endif
